### PR TITLE
chore: dont allow user to select text on website

### PR DESCRIPTION
**Pull request by KendallDoesCoding**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
also @nairvarun how did you get .xyz domain? you bought it or got it for free?

**Comment by nairvarun** [comment]
can you explain why change is required?
<br>

> also @nairvarun how did you get .xyz domain? you bought it or got it for free?

bought it

**Comment by KendallDoesCoding** [comment]
> can you explain why change is required?

well, it makes the user experience better.

**Comment by nairvarun** [comment]
i'm sorry i don't see the utility

**Pull request closed without merging**
