### PR TITLE
Added projects tab

### LINKED ISSUE #4: [FEATURE REQUEST] - Add a projects tab

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Fixes #4 

Added project tab.

If users click the tab, they will see your 4 projects, if they tap it, it will take them to the github page of that project, and if they hover, will show the github url with the https://.

Final edits deploy: https://projects-tab.netlify.app

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@nairvarun Let me know if I should link this project too in that tab.

**Comment by KendallDoesCoding** [comment]
I didn't inculde dots or eva, because I think their just your self-note repos and not projects as of such. Let me know if I should inculde them.

**Comment by nairvarun** [comment]
oh sick! i'll merge it for now but i dont think i'll make this the main look. as for this repo, this was mostly just to test a few things so i probably wont update anything over here.

> I didn't inculde dots or eva, because I think their just your self-note repos and not projects as of such. Let me know if I should inculde them.

yeah i wouldn't include those

**Comment by KendallDoesCoding** [comment]
> oh sick! i'll merge it for now but i dont think i'll make this the main look. as for this repo, this was mostly just to test a few things so i probably wont update anything over here.

Ok cool! Depending on how hard the code is for your new portfolio, I'll see if I'll be able to help you.

> > I didn't inculde dots or eva, because I think their just your self-note repos and not projects as of such. Let me know if I should inculde them.
> 
> yeah i wouldn't include those

Ok cool! I thought so!

**Comment by KendallDoesCoding** [comment]
@nairvarun Just a heads up, I also made a projects.css, but you can merge it into the main css file, I can do that too if you want.

**Comment by nairvarun** [comment]
nah it fine. dont worry about updating this repo. if i ever make any changes it's gonna be on the [gitlab repo](https://nairvarun.gitlab.io/)

> Ok cool! Depending on how hard the code is for your new portfolio, I'll see if I'll be able to help you.

thanks man. i really appreciate it. 
i dont think anything i code is gonna be too hard for you :)

**Pull request merged**
