### PR TITLE
Format HTML, CSS, JS

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
I have formatted the HTML, CSS, JS in the main directory.

If you require it done in the _old directory too, let me know!

### CODE REVIEW

**Comment by nairvarun** [comment]
done :+1:

**Comment by KendallDoesCoding** [comment]
> done 👍

why didn't you merge PR bro.

**Comment by nairvarun** [comment]
auto-formatted while making other changes

**Comment by KendallDoesCoding** [comment]
> auto-formatted while making other changes

ok, noo issues.

**Pull request closed without merging**
